import type {Metadata} from "next";
import "@/styles/globals.css";
import {ReactNode} from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: ReactNode;
}>): ReactNode {
    return (
        <html lang='en'>
        <body className='min-h-full flex flex-col'>{children}</body>
        </html>
    );
}
