import type { Metadata } from "next";
import "@/styles/globals.css";
import { ReactNode } from "react";
import Header from "@/features/header/Header";
import Footer from "@/features/footer/Footer";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: ReactNode;
}>): ReactNode {
   return (
      <html lang="en">
         <body className="container mx-auto min-h-screen flex flex-col bg-gray-200 text-gray-700">
            <Header />

            <main className={"flex-1"}>{children}</main>

            <Footer />
         </body>
      </html>
   );
}
